version: "3.7"

x-env: &app
  build: "./.docker/php"
  working_dir: "/app"
  volumes:
    - ".:/app:cached"
    - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
  tty: true

x-env: &node
  image: node:13.8.0-alpine
  working_dir: "/app"
  volumes:
    - "./:/app:cached"
  tty: true

services:
  nginx:
    build: "./.docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./public:/app/public"
    depends_on:
      - app

  app:
    <<: *app
    depends_on:
      - mysql

  node:
    <<: *node

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "mysql_store:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis_store:/data"

  queue_worker:
    build: "./.docker/php"
    working_dir: "/app"
    command: "php artisan queue:work --tries=3"
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"

  asset_watcher:
    <<: *node
    command: "yarn run watch-poll"
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - "./storage/minio:/storage"
    command: server /storage
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      MINIO_REGION: ap-northeast-1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9090:80"

volumes:
  mysql_store:
  redis_store:
